// Used for defining special keys like ctrl, shift and co
export enum SpecialKeys {
    SHIFT = 'SHIFT',
    ALT = 'ALT',
    CTRL = 'CTRL',
    LWIN = 'LWIN',
    SPACE = 'SPACE',
    ESCAPE='{ESC}',
    HOME='{HOME}',
    RETURN = 'RETURN',
    CURSOR_UP='{UP}',
    CURSOR_DOWN='{DOWN}',
    CURSOR_LEFT='{LEFT}',
    CURSOR_RIGHT='{RIGHT}',
    BACKSPACE='{BACKSPACE}',
    PLUS='{PLUS}',
    MINUS='{MINUS}',
    DIV='{DIV}',
    DELETE='{DEL}',
    TAB='{TAB}',
    F1 = '{F1}',
    F2 = '{F2}',
    F3 = '{F3}',
    F4 = '{F4}',
    F5 = '{F5}',
    F6 = '{F6}',
    F7 = '{F7}',
    F8 = '{F8}',
    F9 = '{F9}',
    F10 = '{F10}',
    F11 = '{F11}',
    F12 = '{F12}',
    INS = 'INS'
}