// Used for defining special keys like ctrl, shift and co
export enum SpecialKeys {
    SHIFT = 'SHIFT',
    ALT = 'ALT',
    CTRL = 'CTRL',
    LWIN = 'LWIN',
    SPACE = 'SPACE',
    ESCAPE='ESCAPE',
    RETURN = 'RETURN',
    CURSOR_UP='CURSOR_UP',
    CURSOR_DOWN='CURSOR_DOWN',
    CURSOR_LEFT='CURSOR_LEFT',
    CURSOR_RIGHT='CURSOR_RIGHT',
    BACK='BACK',
    F1 = 'F1',
    F2 = 'F2',
    F3 = 'F3',
    F4 = 'F4',
    F7 = 'F7',
    F8 = 'F8',
    F9 = 'F9',
    F10 = 'F10',
    F11 = 'F11',
    F12 = 'F12',
}